package chargen_test

import (
	"errors"
	"strings"
	"testing"

	"github.com/philoserf/cschargen/chargen"
)

// TestThePlayerIsAsked. The interactive decider prints the prompt, the
// options and the page they come from, and reads a number.
func TestThePlayerIsAsked(t *testing.T) {
	t.Parallel()

	var out strings.Builder

	player := chargen.NewPlayer(strings.NewReader("2\n"), &out)

	chosen, err := player.Choose(chargen.Choice{
		Point:   "career",
		Prompt:  "Choose a career to attempt",
		Options: []string{"Colonist", "Marine", "Scientist"},
		Cite:    "p. 107",
	})
	if err != nil {
		t.Fatalf("Choose: %v", err)
	}

	if chosen != 1 {
		t.Errorf("chose %d, want 1: the answer was 2 and the list is one-based", chosen)
	}

	asked := out.String()
	for _, want := range []string{
		"Choose a career to attempt", "[p. 107]",
		"1. Colonist", "2. Marine", "3. Scientist",
	} {
		if !strings.Contains(asked, want) {
			t.Errorf("the prompt does not contain %q:\n%s", want, asked)
		}
	}
}

// TestAChoiceInARunSaysWhereItFalls. "Nth and Of place a choice in a run of
// identical ones: a term's skill selections are the same question asked
// several times, and a player answering the fifth cannot otherwise tell it
// from the first."
func TestAChoiceInARunSaysWhereItFalls(t *testing.T) {
	t.Parallel()

	var out strings.Builder

	player := chargen.NewPlayer(strings.NewReader("1\n"), &out)

	_, err := player.Choose(chargen.Choice{
		Prompt: "Assign a rolled score", Options: []string{"8", "9"},
		Nth: 3, Of: 6,
	})
	if err != nil {
		t.Fatalf("Choose: %v", err)
	}

	if !strings.Contains(out.String(), "(3 of 6)") {
		t.Errorf("the prompt does not say where in the run it falls:\n%s", out.String())
	}
}

// TestATypoIsNotAnAbandonedSession. An answer that is not a number, or not
// in range, is asked again.
func TestATypoIsNotAnAbandonedSession(t *testing.T) {
	t.Parallel()

	var out strings.Builder

	player := chargen.NewPlayer(strings.NewReader("banana\n0\n9\n2\n"), &out)

	chosen, err := player.Choose(chargen.Choice{
		Prompt: "Choose", Options: []string{"first", "second"},
	})
	if err != nil {
		t.Fatalf("Choose: %v", err)
	}

	if chosen != 1 {
		t.Errorf("chose %d, want 1", chosen)
	}

	if strings.Count(out.String(), "a number from 1 to 2, please") != 3 {
		t.Errorf("three bad answers should have drawn three corrections:\n%s", out.String())
	}
}

// TestAPlayerWhoStopsAnswering ends generation rather than falling back on
// a default -- which is what the Decider interface says an error means.
func TestAPlayerWhoStopsAnswering(t *testing.T) {
	t.Parallel()

	var out strings.Builder

	player := chargen.NewPlayer(strings.NewReader(""), &out)

	_, err := player.Choose(chargen.Choice{
		Prompt: "Choose", Options: []string{"first", "second"},
	})
	if !errors.Is(err, chargen.ErrPlayerGone) {
		t.Errorf("err = %v, want ErrPlayerGone", err)
	}
}

// TestAChoiceWithOneOptionIsNotAChoice. The engine mostly declines to ask
// those, but a table that narrowed to one still arrives here -- and asking
// would be a question with one answer.
func TestAChoiceWithOneOptionIsNotAChoice(t *testing.T) {
	t.Parallel()

	var out strings.Builder

	player := chargen.NewPlayer(strings.NewReader(""), &out)

	chosen, err := player.Choose(chargen.Choice{
		Prompt: "Choose", Options: []string{"the only one"},
	})
	if err != nil || chosen != 0 {
		t.Fatalf("Choose = %d, %v", chosen, err)
	}

	if !strings.Contains(out.String(), "the only option") {
		t.Errorf("the player was not told why they were not asked:\n%s", out.String())
	}
}

// TestAChoiceWithNoOptions is a bug in the engine rather than a rule, and
// comes back as one.
func TestAChoiceWithNoOptions(t *testing.T) {
	t.Parallel()

	player := chargen.NewPlayer(strings.NewReader(""), &strings.Builder{})

	_, err := player.Choose(chargen.Choice{Prompt: "Choose"})
	if !errors.Is(err, chargen.ErrNoOptions) {
		t.Errorf("err = %v, want ErrNoOptions", err)
	}
}

// TestAnInteractiveRecordReplays. A record generated by asking is the same
// file an auto one is, and the transcript says who decided each choice.
func TestAnInteractiveRecordReplays(t *testing.T) {
	t.Parallel()

	answers := strings.Repeat("1\n", 500)

	opts := options(t, 3)

	opts.Decider = chargen.NewPlayer(strings.NewReader(answers), &strings.Builder{})
	opts.Inputs.TermLimit = 2

	character := generate(t, opts)

	asked := 0

	for _, event := range character.Events {
		if event.Kind != chargen.EventChoice {
			continue
		}

		asked++

		if event.Choice.Decider != chargen.DeciderPlayer {
			t.Errorf("a choice was decided by %q", event.Choice.Decider)
		}
	}

	if asked == 0 {
		t.Fatal("an interactive run asked nothing")
	}

	again := options(t, 3)

	again.Decider = chargen.NewReplay(character.Events)
	again.Inputs = character.Provenance.Inputs

	replayed := generate(t, again)
	if replayed.State.Characteristics != character.State.Characteristics {
		t.Error("an interactive record did not replay to the same character")
	}
}

// brokenWriter fails every write, which is what a closed pipe looks like to
// a prompt.
type brokenWriter struct{}

func (brokenWriter) Write([]byte) (int, error) { return 0, errBrokenPipe }

var errBrokenPipe = errors.New("the prompt went nowhere")

// TestAPromptThatCannotBePrinted. A question the player never saw is not a
// question, so a write that does not land ends generation rather than
// reading an answer to it.
func TestAPromptThatCannotBePrinted(t *testing.T) {
	t.Parallel()

	player := chargen.NewPlayer(strings.NewReader("1\n"), brokenWriter{})

	_, err := player.Choose(chargen.Choice{
		Prompt: "Choose", Options: []string{"first", "second"},
	})
	if !errors.Is(err, errBrokenPipe) {
		t.Errorf("err = %v, want the write failure", err)
	}
}

// TestAChoiceWithOneOptionThatCannotBePrinted is the same, on the branch
// that does not ask.
func TestAChoiceWithOneOptionThatCannotBePrinted(t *testing.T) {
	t.Parallel()

	player := chargen.NewPlayer(strings.NewReader(""), brokenWriter{})

	_, err := player.Choose(chargen.Choice{
		Prompt: "Choose", Options: []string{"the only one"},
	})
	if !errors.Is(err, errBrokenPipe) {
		t.Errorf("err = %v, want the write failure", err)
	}
}

// TestALastAnswerThatIsWrong. Input that ends on a bad answer draws the
// correction and then ends the session, rather than looping on nothing.
func TestALastAnswerThatIsWrong(t *testing.T) {
	t.Parallel()

	var out strings.Builder

	// No trailing newline, so the read returns the text and io.EOF at once.
	player := chargen.NewPlayer(strings.NewReader("banana"), &out)

	_, err := player.Choose(chargen.Choice{
		Prompt: "Choose", Options: []string{"first", "second"},
	})
	if !errors.Is(err, chargen.ErrPlayerGone) {
		t.Errorf("err = %v, want ErrPlayerGone", err)
	}

	if !strings.Contains(out.String(), "a number from 1 to 2, please") {
		t.Errorf("the player was not told what was wrong:\n%s", out.String())
	}
}
